#!/bin/bash
#
# requires:
#  bash
#  dirname, pwd, basename
#  initctl
#
set -e

## variables

readonly abs_path=$(cd $(dirname $0) && pwd)

### ucarp

role=$(basename ${abs_path})
role=${role##vip-}
role=${role%%.d}

### ha-dcmgr

case "${role}" in
up) cmd=start
  ${abs_path}/rabbitmq $*
  initctl ${cmd} vdc-collector RUN=yes
  ;;
down) cmd=stop
  initctl ${cmd} vdc-collector RUN=yes
  ${abs_path}/rabbitmq $*
  ;;
esac
