source :rubygems

gem 'rake', '0.9.2.2'
gem "sequel", "3.36.1"
gem 'json'
gem 'mysql2','0.3.11'
gem "sinatra", "1.3.2"
gem "sinatra-contrib", "1.3.1"
gem 'weary', '1.0.2'

# we have client/ruby-hijiki directory in development environment.
# so we use the local version of hijiki during development.
hijiki_root=File.expand_path('../../../client/ruby-hijiki/', __FILE__)
if File.exists?(hijiki_root)
  gem 'ruby-hijiki', :path=>hijiki_root
else
  gem 'ruby-hijiki', '0.0.3'
end

group :production do
  gem 'unicorn', '4.3.0'
end
