#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

begin
  require "rubygems"
  require "bundler/setup"
rescue LoadError => e
end

require File.join(File.expand_path('../../', __FILE__), 'lib/dolphin')

require 'irb'
IRB.start
