
source "http://rubygems.org"

gem 'rake', '0.9.2.2'
gem 'extlib', '0.9.15'
gem 'configuration'
gem 'ruby-hmac'
gem 'ipaddress', '0.8.0'
gem 'thor', '0.14.6'
gem 'rbvmomi', '1.5.1'
gem 'unicorn', '4.3.0'
gem "sequel", "3.34.1"
gem "mysql", '>= 0.2.8' # leave until mysql2 transition complete.
gem "mysql2", "0.3.11"
gem "rack", "1.4.1"
gem "sinatra", "1.3.2"
gem "sinatra-contrib", "1.3.1"
gem "json", ">= 1.2.0"
gem "net-dhcp", ">= 1.1.0"
gem "bit-struct", ">= 0.13.6"
gem "racket", ">= 1.0.11"

gem 'isono', '0.2.11'
