# -*- coding: utf-8 -*-

require 'rubygems'
require 'bundler/setup'
$:.unshift 'lib'

require 'rake/clean'
require 'dcmgr'

task :default => :spec

desc 'Run specs'
task :spec do
  sh "bundle exec spec -fs -c -r spec/specformat_silent spec"
end

namespace :spec do
  desc 'Run specs, detail mode'
  task :detail do
    sh "bundle exec spec -fs -b -c -r spec/specformat_detail spec"
  end
end

task :environment do
  Dcmgr.configure 'dcmgr.conf'
  Dcmgr.run_initializers
end

task :shell do
  sh "bundle exec ruby lib/dcmgr/shell.rb dcmgr.conf"
end

namespace :shell do
  task :client do
    sh "bundle exec ruby lib/dcmgr/shell.rb -client"
  end
end

task :run do
  desc 'Run server for public'
  sh "bundle exec shotgun -p 3000 web/public/config.ru"
end

namespace :run do
  desc 'Run server for private'
  task :private do
    sh "bundle exec shotgun -p 3000 web/private/config.ru"
  end
end

def input(disp, empty=false)
  print disp
  while buf = STDIN.gets
    break if buf and (buf.length > 0 or empty)
  end
  
  buf.chomp
end

desc 'Create super user'
task :createsuperuser => [ :environment ] do
  user = input("Username: ")
  exit unless user
  system "stty -echo"
  begin
    passwd = input("Password: ")
    puts
    passwd_again = input("Password (again): ", true)
    puts
  end while passwd != passwd_again
  system "stty echo"
  
  Dcmgr::Schema.createsuperuser(user, passwd)
end

namespace :db do
  desc 'Create all database tables'
  task :init => [ :environment ] do
    Dcmgr::Schema.create!
  end

  desc 'Drop all database tables'
  task :drop => [ :environment ] do
    Dcmgr::Schema.drop!
  end

  desc 'Create sample data'
  task :sample_data => [ :environment ] do
    Dcmgr::Schema.load_data 'fixtures/sample_data'
  end

  desc 'Install a range of ip addrs and paired mac addr together'
  task :install_ip => [:environment] do
    require 'dcmgr'
    require 'ipaddr'
    ip_group = Dcmgr::Models::IpGroup.find(:name=>ENV['IP_GROUP']) || abort("No such ip group: #{ENV['IP_GROUP']}")
    ip_start = IPAddr.new(ENV['IP_BEGIN'])
    range_num = ENV['RANGE'].to_i
    # mac vendor address is generated among the local address space. (2,6,a,e)
    vendor_mac = ENV['VENDOR_MAC'] || [("%x%x" % [rand(0xf), %w(0x2 0x6 0xa 0xe)[rand(3).to_i]]),
                                       ("%02x" % rand(0xff)),
                                       ("%02x" % rand(0xff))
                                      ].join(':')
    Dcmgr::Models::Ip.db.transaction do
      range_num.times { |n|
        ip_cur = IPAddr.new(ip_start.to_i + n, Socket::AF_INET)
        #random mac addr generation for three lower digits.
        lower_mac = Array.new(3).map{"%02x" % rand(0xff) }.join(':')
        Dcmgr::Models::Ip.create({:ip=>ip_cur.to_s, :mac=>[vendor_mac, lower_mac].join(':'), :ip_group_id=>ip_group.id,:status=>0})
      }
    end
  end

  task :reset => [ :drop, :init ]
end

desc "Generate dnsmasq.conf has mac and ip address pair."
task :gen_dnsmasq => [:environment] do
  require 'dcmgr'
  require 'erb'
  iplist = Dcmgr::Models::Ip.all
  File.open('dnsmasq.conf', 'w') { |f|
    f << ERB.new(<<'_EOS_', nil, '-').result(binding)
<%- iplist.each do |ip| -%>
dhcp-host=<%= ip[:mac] %>,<%= ip[:ip] %>
<%- end -%>
_EOS_
  }
end

namespace :dbnew do
  desc 'Create all database tables'
  task :init => [ :environment ] do
    require 'sequel'
    require 'isono'
    #if driver is mysql
    Sequel::MySQL.default_charset = 'utf8'
    Sequel::MySQL.default_engine = 'InnoDB'
    #end
    
    Dcmgr::Models::CREATE_TABLE_CLASSES.each { |c|
      Dcmgr::Models.const_get(c).create_table!
    }
    Isono::Models::NodeState.create_table!
    Isono::Models::JobState.create_table!

    Dcmgr::Models::CREATE_TABLE_CLASSES.each { |c|
      Dcmgr::Models.const_get(c).install_data
    }
  end

  desc 'Drop all database tables'
  task :drop => [ :environment ] do
    require 'sequel'
    require 'isono'
    
    Dcmgr::Models::CREATE_TABLE_CLASSES.each { |c|
      Dcmgr::Models.const_get(c).drop_table
    }
    Isono::Models::NodeState.drop_table
    Isono::Models::JobState.drop_table
  end
end

desc 'run bundle command to install vendored gems.'
task :bundle do
  sh <<_ENDCMD
mkdir .bundle
cat <<END_ > .bundle/config
---
BUNDLE_DISABLE_SHARED_GEMS: "1"
BUNDLE_PATH: vendor/bundle
END_
_ENDCMD
  sh "bundle install"
end

