#!/bin/sh
#
# Start/stop hvc.
#
# chkconfig: - 98 9
# description: hvc
# processname: hvc
# pidfile: /var/run/hvc.pid

NAME=hvc
USER=wakame
GROUP=wakame
PIDFILE=/var/run/$NAME.pid

. /etc/rc.d/init.d/functions
[ -f /etc/default/wakame ] && {
	. /etc/default/wakame
	export WAKAME_ROOT WAKAME_ENV
}

DAEMON=$WAKAME_ROOT/bin/$NAME

case "$1" in
	start)
		echo -n $"Starting $NAME: "
		[ -f $PIDFILE ] && ps -c `cat $PIDFILE` >/dev/null && success && echo && exit 0
		$DAEMON -u $USER $OPTIONS && success || failure
		RETVAL=$?
		echo
		;;
	stop)
		echo -n $"Stopping $NAME: "
		[ -f $PIDFILE ] || { success; echo; exit 0; }
		kill `cat $PIDFILE` && success || failure
		RETVAL=$?
		rm -f $PIDFILE
		echo
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo $"Usage: $0 [start|stop|restart]"
		RETVAL=1
		;;
esac
exit $RETVAL
