#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'net/http'
require 'uri'
require 'json'
require 'time'

start_time = URI.encode((Time.now - 60).iso8601)

host = ENV['DOLPHIN_HOST'] || '127.0.0.1'
port = ENV['DOLPHIN_PORT'] || 9004

path = "http://#{host}:#{port}/events"
# path = "http://#{host}:#{port}/events?limit=10&start_time=#{start_time}"
# path = 'http://#{host}:#{port}/events?start_id=12174a14-87c1-11e2-927c-31035db8d436'

uri = URI.parse(path)

headers = {
  'Content-Type' =>'application/json',
}

request = Net::HTTP::Get.new(uri.request_uri, headers)
http = Net::HTTP.new(uri.host, uri.port)
http.set_debug_output $stderr
http.start do |h|
  response = h.request(request)
  res = JSON.parse(response.body)
  p res
end
