#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'net/http'
require 'uri'
require 'json'

host = ENV['DOLPHIN_HOST'] || '127.0.0.1'
port = ENV['DOLPHIN_PORT'] || 9004

path = "http://#{host}:#{port}/notifications"

uri = URI.parse(path)

headers = {
  'Content-Type' =>'application/json',
  'X-Notification-Id' => 'system',
}

request = Net::HTTP::Get.new(uri.request_uri, headers)
http = Net::HTTP.new(uri.host, uri.port)
http.set_debug_output $stderr
http.start do |h|
  response = h.request(request)
  res = JSON.parse(response.body)
  p res
end
