
require 'sequel'
require File.expand_path('../config/path_resolver', __FILE__)

M = Isono::Manifest.load_file('master.isono')

namespace :db do
  
  task :setup do
    db = Sequel.connect(M.config.data_store.database_dsn)
    Isono::Models::AgentPool.create_table?
    Isono::Models::ResourceInstance.create_table?
    Isono::Models::EventLog.create_table?
  end

  task :reset => [:drop, :setup]
  
  task :drop do
  end
  
end
