# -*- coding: utf-8 -*-
require 'rake/clean'
$:.unshift 'lib'
require 'lib/dcmgr_api'
Frontend::DcmgrApi::configure('api.conf')

namespace :db do
  desc 'Create all database tables'
  task :init => [:environment] do
    Frontend::Schema.create!
  end

  desc 'Delete all database tables'
  task :drop => [:environment] do
    Frontend::Schema.drop!
  end
  
  desc 'Create user'
  task :create_user => [:environment] do
    user = Frontend::Models::User.new
    user.uuid = user.canonical_uuid
    user.login_id = 'test'
    user.password = 'password'
    user.primary_account_id = 1
    user.save
  end
  
  desc 'Create account'
  task :create_account => [:environment] do
    account = Frontend::Models::Account.new
    account.uuid = account.canonical_uuid
    account.name = 'dcmgr'
    account.enable = 1
    account.save
  end

  desc 'Mapping authorization'
  task :mapping_authz => [:environment] do
    authz = Frontend::Models::Authz.new
    authz.user_id = 1
    authz.account_id = 1
    authz.type_id = 90001 #ModifyAccount
    authz.save
  end
end

task :environment do
  p 'todo:environemt initializer'
end