#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'dcmgr/rubygems'
require 'dcmgr'

Dcmgr.configure(File.expand_path('../../config/dcmgr.conf', __FILE__))
Dcmgr.run_initializers

require 'irb'
include Dcmgr
IRB.start
