source :rubygems

gem 'rails', '3.0.19'
gem 'sequel','3.43.0'
gem 'json'
gem 'oauth','0.4.1'
gem 'nokogiri', '1.5.6'
gem 'rake', '10.0.3'
gem 'thor'
gem 'mysql2','0.3.11'
gem 'ripl'
gem 'rack-cors', :require => 'rack/cors'

# we have client/ruby-hijiki directory in development environment.
# so we use the local version of hijiki during development.
hijiki_root=File.expand_path('../../../client/ruby-hijiki/', __FILE__)
if File.exists?(hijiki_root)
  gem 'ruby-hijiki', :path=>hijiki_root
else
  gem 'ruby-hijiki', '0.0.3'
end

group :production do
  gem 'unicorn', '4.5.0'
end
