source :rubygems

gem 'rails', '3.0.11'
gem 'sequel','3.34.1'
gem 'json','1.6.3'
gem 'oauth','0.4.1'
gem 'nokogiri', '1.4.4'
gem 'rake', '0.9.2.2'
gem 'thor', '0.14.6'
gem 'mysql2','0.3.11'

group :production do
  gem 'unicorn', '4.3.0'
end
