source :rubygems

gem 'rails', '3.0.11'
gem 'mysql','2.8.1'
gem 'sequel','3.27.0'
gem 'json','1.6.3'
gem 'oauth','0.4.1'
gem 'nokogiri', '1.4.4'
gem 'rake', '0.9.2'
gem 'thor', '0.14.6'

group :production do
  gem 'unicorn', '4.1.1'
end
