# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'
require 'rake/clean'
CLOBBER.include("vendor/bundle/**/*")

DcmgrGui::Application.load_tasks

$LOAD_PATH.unshift File.expand_path('../../../dcmgr/lib', __FILE__)

desc "build gem packages"
task :gem do
  require 'rubygems'
  require 'rake/gempackagetask'
  require 'dcmgr/version'
  
  spec = Gem::Specification.new do |s|
    s.platform = Gem::Platform::RUBY
    s.version = Dcmgr::VERSION
    s.authors = ['axsh Ltd.']
    s.email = ['dev@axsh.net']
    s.name = 'wakame-vdc-webui'
    s.summary = "Wakame-VDC: UI frontend"
    s.description = 'Datacenter Hypervisor'
    s.required_ruby_version = '>= 2.0.0'

    s.files = Dir['app/**/*.{rb,erb}','lib/**/*.rb',
                  'config/**/*.{rb,yml}', 'db/**/*.rb',
                  'extras/**/*.rb', 'public/**/*.*',
                  'lib/**/*.{rb,rake}', 'test/**/*.rb',
                  'vendor/plugins/**/*.*', 'tmp/',
                  'script/*', 'test/**/*.rb', 'doc/**/*.*'] +
      %w(Rakefile config.ru LICENSE NOTICE INSTALL.txt INSTALL-API.txt tmp)

    s.add_dependency "rails", '3.0.11'
    s.add_dependency 'mysql','2.8.1'
    s.add_dependency 'sequel','3.27.0'
    s.add_dependency 'json','1.6.3'
    s.add_dependency 'oauth','0.4.1'
    s.add_dependency 'nokogiri', '1.4.4'
    s.add_dependency 'thor', '0.14.6'
  end
  
  File.open("#{spec.name}.gemspec", 'w'){|f| f.write(spec.to_ruby) }
  sh "gem build #{spec.name}.gemspec"
end
