# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'
require 'rake/clean'
CLOBBER.include("vendor/bundle/**/*")

DcmgrGui::Application.load_tasks

$LOAD_PATH.unshift File.expand_path('../../../dcmgr/lib', __FILE__)
