require 'rubygems'
#GEMSPEC = Gem::Specification.load('ruby-vdc.gemspec')

desc "Build ruby-vdc, then run tests."
task :default => [:test]

desc 'Generate documentation'
begin
  require 'yard'
  YARD::Rake::YardocTask.new do |t|
    t.files   = ['lib/**/*.rb', '-', 'docs/*.md']
  end
rescue LoadError
  task :yard do puts "Please install yard first!"; end
end

task :test do
  sh %{cd test && ruby ts_all.rb}
end
